In [3]:
#import necessary libraries
import pandas as pd
from chembl_webresource_client.new_client import new_client

In [4]:
#Target search for coronavirus
target = new_client.target
target_query = target.search('coronavirus')
targets = pd.DataFrame.from_dict(target_query)
targets

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Coronavirus,Coronavirus,17.0,False,CHEMBL613732,[],ORGANISM,11119
1,[],Feline coronavirus,Feline coronavirus,14.0,False,CHEMBL612744,[],ORGANISM,12663
2,[],Murine coronavirus,Murine coronavirus,14.0,False,CHEMBL5209664,[],ORGANISM,694005
3,[],Canine coronavirus,Canine coronavirus,14.0,False,CHEMBL5291668,[],ORGANISM,11153
4,[],Human coronavirus 229E,Human coronavirus 229E,13.0,False,CHEMBL613837,[],ORGANISM,11137
5,[],Human coronavirus OC43,Human coronavirus OC43,13.0,False,CHEMBL5209665,[],ORGANISM,31631
6,[],Severe acute respiratory syndrome-related coro...,SARS coronavirus 3C-like proteinase,10.0,False,CHEMBL3927,"[{'accession': 'P0C6U8', 'component_descriptio...",SINGLE PROTEIN,694009
7,[],Middle East respiratory syndrome-related coron...,Middle East respiratory syndrome-related coron...,9.0,False,CHEMBL4296578,[],ORGANISM,1335626
8,[],Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1ab,4.0,False,CHEMBL5118,"[{'accession': 'P0C6X7', 'component_descriptio...",SINGLE PROTEIN,694009
9,[],Severe acute respiratory syndrome coronavirus 2,Replicase polyprotein 1ab,4.0,False,CHEMBL4523582,"[{'accession': 'P0DTD1', 'component_descriptio...",SINGLE PROTEIN,2697049

In [5]:
selected_target = targets.target_chembl_id[6]
selected_target

'CHEMBL3927'

In [6]:
activity = new_client.activity
res = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")
df = pd.DataFrame.from_dict(res)
df.head(3)

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,1480935,[],CHEMBL829584,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,SARS coronavirus 3C-like proteinase,694009,None,None,IC50,uM,UO_0000065,None,7.2
1,None,None,1480936,[],CHEMBL829584,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,SARS coronavirus 3C-like proteinase,694009,None,None,IC50,uM,UO_0000065,None,9.4
2,None,None,1481061,[],CHEMBL830868,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,SARS coronavirus 3C-like proteinase,694009,None,None,IC50,uM,UO_0000065,None,13.5

In [7]:
df.standard_type.unique()
df.to_csv('bioactivity_data.csv', index=False)

In [8]:
file_path = 'bioactivity_data.csv'
data = pd.read_csv(file_path)
print(data.head())

  action_type activity_comment  activity_id activity_properties  \
0         NaN              NaN      1480935                  []
1         NaN              NaN      1480936                  []
2         NaN              NaN      1481061                  []
3         NaN              NaN      1481065                  []
4         NaN              NaN      1481066                  []

  assay_chembl_id                                  assay_description  \
0    CHEMBL829584  In vitro inhibitory concentration against SARS...
1    CHEMBL829584  In vitro inhibitory concentration against SARS...
2    CHEMBL830868  In vitro inhibitory concentration against SARS...
3    CHEMBL829584  In vitro inhibitory concentration against SARS...
4    CHEMBL829584  In vitro inhibitory concentration against SARS...

  assay_type  assay_variant_accession  assay_variant_mutation bao_endpoint  \
0          B                      NaN                     NaN  BAO_0000190
1          B                      NaN                     NaN  BAO_0000190
2          B                      NaN                     NaN  BAO_0000190
3          B                      NaN                     NaN  BAO_0000190
4          B                      NaN                     NaN  BAO_0000190

   ...                                    target_organism  \
0  ...  Severe acute respiratory syndrome-related coro...
1  ...  Severe acute respiratory syndrome-related coro...
2  ...  Severe acute respiratory syndrome-related coro...
3  ...  Severe acute respiratory syndrome-related coro...
4  ...  Severe acute respiratory syndrome-related coro...

                      target_pref_name target_tax_id text_value toid  type  \
0  SARS coronavirus 3C-like proteinase        694009        NaN  NaN  IC50
1  SARS coronavirus 3C-like proteinase        694009        NaN  NaN  IC50
2  SARS coronavirus 3C-like proteinase        694009        NaN  NaN  IC50
3  SARS coronavirus 3C-like proteinase        694009        NaN  NaN  IC50
4  SARS coronavirus 3C-like proteinase        694009        NaN  NaN  IC50

  units    uo_units upper_value  value
0    uM  UO_0000065         NaN   7.20
1    uM  UO_0000065         NaN   9.40
2    uM  UO_0000065         NaN  13.50
3    uM  UO_0000065         NaN  13.11
4    uM  UO_0000065         NaN   2.00

[5 rows x 46 columns]

In [9]:
df2 = df[df.standard_value.notna()]
df2 =  df2[df.canonical_smiles.notna()]
df2
#no missing data in this dataset but this is standard procedure for any target protein

C:\Users\ameen\AppData\Local\Temp\ipykernel_14956\1207616509.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 =  df2[df.canonical_smiles.notna()]

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,1480935,[],CHEMBL829584,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,SARS coronavirus 3C-like proteinase,694009,None,None,IC50,uM,UO_0000065,None,7.2
1,None,None,1480936,[],CHEMBL829584,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,SARS coronavirus 3C-like proteinase,694009,None,None,IC50,uM,UO_0000065,None,9.4
2,None,None,1481061,[],CHEMBL830868,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,SARS coronavirus 3C-like proteinase,694009,None,None,IC50,uM,UO_0000065,None,13.5
3,None,None,1481065,[],CHEMBL829584,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,SARS coronavirus 3C-like proteinase,694009,None,None,IC50,uM,UO_0000065,None,13.11
4,None,None,1481066,[],CHEMBL829584,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,SARS coronavirus 3C-like proteinase,694009,None,None,IC50,uM,UO_0000065,None,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242,"{'action_type': 'INHIBITOR', 'description': 'N...",None,25516041,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5336133,Inhibition of SARS-CoV N-terminal 6His-SUMO-ta...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,SARS coronavirus 3C-like proteinase,694009,None,None,pIC50,None,UO_0000065,None,6.42
243,"{'action_type': 'INHIBITOR', 'description': 'N...",None,25516042,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5336133,Inhibition of SARS-CoV N-terminal 6His-SUMO-ta...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,SARS coronavirus 3C-like proteinase,694009,None,None,IC50,uM,UO_0000065,None,0.165
244,"{'action_type': 'INHIBITOR', 'description': 'N...",None,25516043,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5336133,Inhibition of SARS-CoV N-terminal 6His-SUMO-ta...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,SARS coronavirus 3C-like proteinase,694009,None,None,IC50,uM,UO_0000065,None,0.161
245,"{'action_type': 'INHIBITOR', 'description': 'N...",None,25516044,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5336133,Inhibition of SARS-CoV N-terminal 6His-SUMO-ta...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,SARS coronavirus 3C-like proteinase,694009,None,None,pIC50,None,UO_0000065,None,6.78
246,"{'action_type': 'INHIBITOR', 'description': 'N...",None,25516045,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5336133,Inhibition of SARS-CoV N-terminal 6His-SUMO-ta...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,SARS coronavirus 3C-like proteinase,694009,None,None,pIC50,None,UO_0000065,None,6.79

In [10]:
len(df2.canonical_smiles.unique())
df2_nr = df2.drop_duplicates(['canonical_smiles'])
df2_nr

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,1480935,[],CHEMBL829584,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,SARS coronavirus 3C-like proteinase,694009,None,None,IC50,uM,UO_0000065,None,7.2
1,None,None,1480936,[],CHEMBL829584,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,SARS coronavirus 3C-like proteinase,694009,None,None,IC50,uM,UO_0000065,None,9.4
2,None,None,1481061,[],CHEMBL830868,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,SARS coronavirus 3C-like proteinase,694009,None,None,IC50,uM,UO_0000065,None,13.5
3,None,None,1481065,[],CHEMBL829584,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,SARS coronavirus 3C-like proteinase,694009,None,None,IC50,uM,UO_0000065,None,13.11
4,None,None,1481066,[],CHEMBL829584,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,SARS coronavirus 3C-like proteinase,694009,None,None,IC50,uM,UO_0000065,None,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238,None,None,18880176,[],CHEMBL4311688,Inhibition of SARS coronavirus 3Cl protease R1...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,SARS coronavirus 3C-like proteinase,694009,None,None,IC50,uM,UO_0000065,None,1000.0
239,None,None,18880177,[],CHEMBL4311688,Inhibition of SARS coronavirus 3Cl protease R1...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,SARS coronavirus 3C-like proteinase,694009,None,None,IC50,uM,UO_0000065,None,2000.0
241,"{'action_type': 'INHIBITOR', 'description': 'N...",None,25516040,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5336133,Inhibition of SARS-CoV N-terminal 6His-SUMO-ta...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,SARS coronavirus 3C-like proteinase,694009,None,None,IC50,uM,UO_0000065,None,0.383
243,"{'action_type': 'INHIBITOR', 'description': 'N...",None,25516042,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5336133,Inhibition of SARS-CoV N-terminal 6His-SUMO-ta...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,SARS coronavirus 3C-like proteinase,694009,None,None,IC50,uM,UO_0000065,None,0.165
244,"{'action_type': 'INHIBITOR', 'description': 'N...",None,25516043,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5336133,Inhibition of SARS-CoV N-terminal 6His-SUMO-ta...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,SARS coronavirus 3C-like proteinase,694009,None,None,IC50,uM,UO_0000065,None,0.161

In [11]:
#one of the methods to extract columns
#mol_cid = []
#for i in df2.molecule_chembl_id:
#    mol_cid.append(i)
#canonical_smiles = []
#for i in df2.canonical_smiles:
#standard_value = []
#for i in df2.standard_value:
#    standard_value.append(i)

In [12]:
selection = ['molecule_chembl_id','canonical_smiles','standard_value']
df3 = df2_nr[selection]
df3

,molecule_chembl_id,canonical_smiles,standard_value
0,CHEMBL187579,Cc1noc(C)c1CN1C(=O)C(=O)c2cc(C#N)ccc21,7200.0
1,CHEMBL188487,O=C1C(=O)N(Cc2ccc(F)cc2Cl)c2ccc(I)cc21,9400.0
2,CHEMBL185698,O=C1C(=O)N(CC2COc3ccccc3O2)c2ccc(I)cc21,13500.0
3,CHEMBL426082,O=C1C(=O)N(Cc2cc3ccccc3s2)c2ccccc21,13110.0
4,CHEMBL187717,O=C1C(=O)N(Cc2cc3ccccc3s2)c2c1cccc2[N+](=O)[O-],2000.0
...,...,...,...
238,CHEMBL4437284,CON(C)C(=O)[C@H](Cc1c[nH]cn1)NC[C@@H]1C(NC(=O)...,1000000.0
239,CHEMBL4459894,CCOC(=O)/C=C/[C@H](Cc1c[nH]cn1)NC[C@@H]1C(NC(=...,2000000.0
241,CHEMBL4590273,Cc1cccc2nc(CSC(=S)NCc3cccnc3)cn12,383.0
243,CHEMBL5436771,S=C([S-])NCc1cccnc1.[K+],165.0
244,CHEMBL2365410,CC(C)C[C@H](NC(=O)OCc1ccccc1)C(=O)N[C@@H](CC1C...,161.0

In [13]:
bioactivity_threshold = []
for i in df3.standard_value:
  if float(i) >= 10000:
    bioactivity_threshold.append("inactive")
  elif float(i) <= 1000:
    bioactivity_threshold.append("active")
  else:
    bioactivity_threshold.append("intermediate")
     

bioactivity_class = pd.Series(bioactivity_threshold, name='class')
df4 = pd.concat([df3, bioactivity_class], axis=1)
df4

,molecule_chembl_id,canonical_smiles,standard_value,class
0,CHEMBL187579,Cc1noc(C)c1CN1C(=O)C(=O)c2cc(C#N)ccc21,7200.0,intermediate
1,CHEMBL188487,O=C1C(=O)N(Cc2ccc(F)cc2Cl)c2ccc(I)cc21,9400.0,intermediate
2,CHEMBL185698,O=C1C(=O)N(CC2COc3ccccc3O2)c2ccc(I)cc21,13500.0,inactive
3,CHEMBL426082,O=C1C(=O)N(Cc2cc3ccccc3s2)c2ccccc21,13110.0,inactive
4,CHEMBL187717,O=C1C(=O)N(Cc2cc3ccccc3s2)c2c1cccc2[N+](=O)[O-],2000.0,intermediate
...,...,...,...,...
169,NaN,NaN,NaN,inactive
170,NaN,NaN,NaN,intermediate
171,NaN,NaN,NaN,intermediate
172,NaN,NaN,NaN,inactive
173,NaN,NaN,NaN,intermediate

In [14]:
bioactivity_class = pd.Series(bioactivity_threshold, name='class')
df5 = pd.concat([df4, bioactivity_class], axis=1)
df5

,molecule_chembl_id,canonical_smiles,standard_value,class,class
0,CHEMBL187579,Cc1noc(C)c1CN1C(=O)C(=O)c2cc(C#N)ccc21,7200.0,intermediate,intermediate
1,CHEMBL188487,O=C1C(=O)N(Cc2ccc(F)cc2Cl)c2ccc(I)cc21,9400.0,intermediate,intermediate
2,CHEMBL185698,O=C1C(=O)N(CC2COc3ccccc3O2)c2ccc(I)cc21,13500.0,inactive,inactive
3,CHEMBL426082,O=C1C(=O)N(Cc2cc3ccccc3s2)c2ccccc21,13110.0,inactive,inactive
4,CHEMBL187717,O=C1C(=O)N(Cc2cc3ccccc3s2)c2c1cccc2[N+](=O)[O-],2000.0,intermediate,intermediate
...,...,...,...,...,...
169,NaN,NaN,NaN,inactive,inactive
170,NaN,NaN,NaN,intermediate,intermediate
171,NaN,NaN,NaN,intermediate,intermediate
172,NaN,NaN,NaN,inactive,inactive
173,NaN,NaN,NaN,intermediate,intermediate

In [15]:
df5.to_csv('bioactivity_preprocessed_data.csv', index=False)

Lipinski descriptors - evaluates drug likeness of compound
They are based on the key pharmacokinetic properties: absorbtion, distribution, metabolism and excretion (ADME)
Lipinski's Rule states the following:
- molecular weight < 5000 Dalton
- Octanol-water partition coefficient (LogP) < 5
- Hydrogen bond donors < 5
- Hydrogen bond acceptors < 10

In [16]:
import numpy as np
from rdkit import Chem
from rdkit.Chem import Descriptors, Lipinski

In [17]:
df_no_smiles = df5.drop(columns='canonical_smiles')

smiles = []

for i in df5.canonical_smiles.tolist():
    cpd = str(i).split('.')
    cpd_longest = max(cpd, key = len)
    smiles.append(cpd_longest)

smiles = pd.Series(smiles, name = 'canonical_smiles')

df_clean_smiles = pd.concat([df_no_smiles, smiles], axis = 1)
df_clean_smiles

,molecule_chembl_id,standard_value,class,class,canonical_smiles
0,CHEMBL187579,7200.0,intermediate,intermediate,Cc1noc(C)c1CN1C(=O)C(=O)c2cc(C#N)ccc21
1,CHEMBL188487,9400.0,intermediate,intermediate,O=C1C(=O)N(Cc2ccc(F)cc2Cl)c2ccc(I)cc21
2,CHEMBL185698,13500.0,inactive,inactive,O=C1C(=O)N(CC2COc3ccccc3O2)c2ccc(I)cc21
3,CHEMBL426082,13110.0,inactive,inactive,O=C1C(=O)N(Cc2cc3ccccc3s2)c2ccccc21
4,CHEMBL187717,2000.0,intermediate,intermediate,O=C1C(=O)N(Cc2cc3ccccc3s2)c2c1cccc2[N+](=O)[O-]
...,...,...,...,...,...
220,NaN,NaN,NaN,NaN,nan
222,NaN,NaN,NaN,NaN,nan
232,NaN,NaN,NaN,NaN,nan
233,NaN,NaN,NaN,NaN,nan
234,NaN,NaN,NaN,NaN,nan

In [18]:
def lipinski(smiles, verbose=False):

    moldata= []
    for elem in smiles:
        mol=Chem.MolFromSmiles(elem) 
        moldata.append(mol)
       
    baseData= np.arange(1,1)
    i=0  
    for mol in moldata:        
       
        desc_MolWt = Descriptors.MolWt(mol)
        desc_MolLogP = Descriptors.MolLogP(mol)
        desc_NumHDonors = Lipinski.NumHDonors(mol)
        desc_NumHAcceptors = Lipinski.NumHAcceptors(mol)
           
        row = np.array([desc_MolWt,
                        desc_MolLogP,
                        desc_NumHDonors,
                        desc_NumHAcceptors])   
    
        if(i==0):
            baseData=row
        else:
            baseData=np.vstack([baseData, row])
        i=i+1      
    
    columnNames=["MW","LogP","NumHDonors","NumHAcceptors"]   
    descriptors = pd.DataFrame(data=baseData,columns=columnNames)
    
    return descriptors

In [19]:
df_lipinski = lipinski(df_clean_smiles.canonical_smiles)
df_lipinski

[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'
[23:26:51] SMILES Parse Error: syntax error while parsing: nan
[23:26:51] SMILES Parse Error: check for mistakes around position 2:
[23:26:51] nan
[23:26:51] ~^
[23:26:51] SMILES Parse Error: Failed parsing SMILES 'nan' for input: 'nan'

TypeError: No registered converter was able to produce a C++ rvalue of type class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > from this Python object of type float

In [ ]:
df_lipinski

          MW     LogP  NumHDonors  NumHAcceptors
0    281.271  1.89262         0.0            5.0
1    415.589  3.81320         0.0            2.0
2    421.190  2.66050         0.0            4.0
3    293.347  3.63080         0.0            3.0
4    338.344  3.53900         0.0            5.0
..       ...      ...         ...            ...
232      NaN      NaN         NaN            NaN
233      NaN      NaN         NaN            NaN
234      NaN      NaN         NaN            NaN
235      NaN      NaN         NaN            NaN
236      NaN      NaN         NaN            NaN

[237 rows x 4 columns]

In [ ]:
#integrating df_lipinski into df
df_combined = pd.concat([df4, df_lipinski], axis=1)

In [ ]:
df_combined

,molecule_chembl_id,canonical_smiles,standard_value,class,MW,LogP,NumHDonors,NumHAcceptors
0,CHEMBL187579,Cc1noc(C)c1CN1C(=O)C(=O)c2cc(C#N)ccc21,7200.0,intermediate,281.271,1.89262,0.0,5.0
1,CHEMBL188487,O=C1C(=O)N(Cc2ccc(F)cc2Cl)c2ccc(I)cc21,9400.0,intermediate,415.589,3.81320,0.0,2.0
2,CHEMBL185698,O=C1C(=O)N(CC2COc3ccccc3O2)c2ccc(I)cc21,13500.0,inactive,421.190,2.66050,0.0,4.0
3,CHEMBL426082,O=C1C(=O)N(Cc2cc3ccccc3s2)c2ccccc21,13110.0,inactive,293.347,3.63080,0.0,3.0
4,CHEMBL187717,O=C1C(=O)N(Cc2cc3ccccc3s2)c2c1cccc2[N+](=O)[O-],2000.0,intermediate,338.344,3.53900,0.0,5.0
...,...,...,...,...,...,...,...,...
220,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
222,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
232,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
233,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
234,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#convert IC50 to pIC50 scale, negative log transformation
#orginal IC50 values lead to uneven distribution

def pIC50(input):
    pIC50 = []

    for i in input['standard_value_norm']:
        molar = i*(10**-9) #convert nM to M
        pIC50.append(-np.log10(molar))

    input['pIC50'] = pIC50
    x = input.drop('standard_value_norm', axis = 1)

    return x

In [ ]:
df_combined.standard_value.describe()

count         184
unique        120
top       50000.0
freq           13
Name: standard_value, dtype: object

In [ ]:
def norm_value(input):
    norm = []

    for i in input['standard_value']:
        if i > 100000000:
          i = 100000000
        norm.append(i)

    input['standard_value_norm'] = norm
    x = input.drop('standard_value', axis = 1)
        
    return x

In [ ]:
df_norm = norm_value(df_combined)
df_norm

TypeError: '>' not supported between instances of 'str' and 'int'

In [ ]:
df_norm.standard_value_norm.describe()

count    2.450000e+02
mean     6.893878e+04
std      1.851962e+05
min      5.000000e+01
25%      5.000000e+03
50%      1.500000e+04
75%      4.700000e+04
max      2.000000e+06
Name: standard_value_norm, dtype: float64

In [ ]:
df_final = pIC50(df_norm)
df_final

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,units,uo_units,upper_value,value,class,MW,LogP,NumHDonors,NumHAcceptors,pIC50
0,NaN,NaN,1480935.0,[],CHEMBL829584,In vitro inhibitory concentration against SARS...,B,NaN,NaN,BAO_0000190,...,uM,UO_0000065,NaN,7.200,intermediate,281.271,1.89262,0.0,5.0,5.142668
1,NaN,NaN,1480936.0,[],CHEMBL829584,In vitro inhibitory concentration against SARS...,B,NaN,NaN,BAO_0000190,...,uM,UO_0000065,NaN,9.400,intermediate,415.589,3.81320,0.0,2.0,5.026872
2,NaN,NaN,1481061.0,[],CHEMBL830868,In vitro inhibitory concentration against SARS...,B,NaN,NaN,BAO_0000190,...,uM,UO_0000065,NaN,13.500,inactive,421.190,2.66050,0.0,4.0,4.869666
3,NaN,NaN,1481065.0,[],CHEMBL829584,In vitro inhibitory concentration against SARS...,B,NaN,NaN,BAO_0000190,...,uM,UO_0000065,NaN,13.110,inactive,293.347,3.63080,0.0,3.0,4.882397
4,NaN,NaN,1481066.0,[],CHEMBL829584,In vitro inhibitory concentration against SARS...,B,NaN,NaN,BAO_0000190,...,uM,UO_0000065,NaN,2.000,intermediate,338.344,3.53900,0.0,5.0,5.698970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242,"{'action_type': 'INHIBITOR', 'description': 'N...",NaN,25516043.0,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5336133,Inhibition of SARS-CoV N-terminal 6His-SUMO-ta...,B,NaN,NaN,BAO_0000190,...,uM,UO_0000065,NaN,0.161,active,485.559,0.54470,5.0,7.0,6.793174
243,"{'action_type': 'INHIBITOR', 'description': 'N...",NaN,25516044.0,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5336133,Inhibition of SARS-CoV N-terminal 6His-SUMO-ta...,B,NaN,NaN,BAO_0000190,...,NaN,UO_0000065,NaN,6.780,NaN,222.379,-1.99300,1.0,3.0,6.779997
244,"{'action_type': 'INHIBITOR', 'description': 'N...",NaN,25516045.0,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5336133,Inhibition of SARS-CoV N-terminal 6His-SUMO-ta...,B,NaN,NaN,BAO_0000190,...,NaN,UO_0000065,NaN,6.790,NaN,485.559,0.54470,5.0,7.0,6.790003
245,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,inactive,NaN,NaN,NaN,NaN,NaN
246,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,intermediate,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_final.pIC50.describe()

count    245.000000
mean       4.894585
std        0.911338
min        2.698970
25%        4.327902
50%        4.823909
75%        5.301030
max        7.301030
Name: pIC50, dtype: float64

In [ ]:
df_2class = df_final[df_final.bioactivity_class != 'intermediate']
df_2class

AttributeError: 'DataFrame' object has no attribute 'bioactivity_class'